/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarValueReadinessRouteImport } from './../routes/_sidebar/value-readiness'
import { Route as SidebarTaxonomyRouteImport } from './../routes/_sidebar/taxonomy'
import { Route as SidebarSourceSystemsRouteImport } from './../routes/_sidebar/source-systems'
import { Route as SidebarRulesRouteImport } from './../routes/_sidebar/rules'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarKnowledgeRouteImport } from './../routes/_sidebar/knowledge'
import { Route as SidebarGapsRouteImport } from './../routes/_sidebar/gaps'
import { Route as SidebarEditRouteImport } from './../routes/_sidebar/edit'
import { Route as SidebarDataCatalogRouteImport } from './../routes/_sidebar/data-catalog'
import { Route as SidebarDashboardRouteImport } from './../routes/_sidebar/dashboard'
import { Route as SidebarCompanyRouteImport } from './../routes/_sidebar/company'
import { Route as SidebarArtifactsRouteImport } from './../routes/_sidebar/artifacts'
import { Route as SidebarAnalyticsRouteImport } from './../routes/_sidebar/analytics'
import { Route as SidebarAboutRouteImport } from './../routes/_sidebar/about'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarValueReadinessRoute = SidebarValueReadinessRouteImport.update({
  id: '/value-readiness',
  path: '/value-readiness',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarTaxonomyRoute = SidebarTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSourceSystemsRoute = SidebarSourceSystemsRouteImport.update({
  id: '/source-systems',
  path: '/source-systems',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRulesRoute = SidebarRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarKnowledgeRoute = SidebarKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGapsRoute = SidebarGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarEditRoute = SidebarEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDataCatalogRoute = SidebarDataCatalogRouteImport.update({
  id: '/data-catalog',
  path: '/data-catalog',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarCompanyRoute = SidebarCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarArtifactsRoute = SidebarArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAnalyticsRoute = SidebarAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAboutRoute = SidebarAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof SidebarAboutRoute
  '/analytics': typeof SidebarAnalyticsRoute
  '/artifacts': typeof SidebarArtifactsRoute
  '/company': typeof SidebarCompanyRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/data-catalog': typeof SidebarDataCatalogRoute
  '/edit': typeof SidebarEditRoute
  '/gaps': typeof SidebarGapsRoute
  '/knowledge': typeof SidebarKnowledgeRoute
  '/profile': typeof SidebarProfileRoute
  '/rules': typeof SidebarRulesRoute
  '/source-systems': typeof SidebarSourceSystemsRoute
  '/taxonomy': typeof SidebarTaxonomyRoute
  '/value-readiness': typeof SidebarValueReadinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof SidebarAboutRoute
  '/analytics': typeof SidebarAnalyticsRoute
  '/artifacts': typeof SidebarArtifactsRoute
  '/company': typeof SidebarCompanyRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/data-catalog': typeof SidebarDataCatalogRoute
  '/edit': typeof SidebarEditRoute
  '/gaps': typeof SidebarGapsRoute
  '/knowledge': typeof SidebarKnowledgeRoute
  '/profile': typeof SidebarProfileRoute
  '/rules': typeof SidebarRulesRoute
  '/source-systems': typeof SidebarSourceSystemsRoute
  '/taxonomy': typeof SidebarTaxonomyRoute
  '/value-readiness': typeof SidebarValueReadinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/about': typeof SidebarAboutRoute
  '/_sidebar/analytics': typeof SidebarAnalyticsRoute
  '/_sidebar/artifacts': typeof SidebarArtifactsRoute
  '/_sidebar/company': typeof SidebarCompanyRoute
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/data-catalog': typeof SidebarDataCatalogRoute
  '/_sidebar/edit': typeof SidebarEditRoute
  '/_sidebar/gaps': typeof SidebarGapsRoute
  '/_sidebar/knowledge': typeof SidebarKnowledgeRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/rules': typeof SidebarRulesRoute
  '/_sidebar/source-systems': typeof SidebarSourceSystemsRoute
  '/_sidebar/taxonomy': typeof SidebarTaxonomyRoute
  '/_sidebar/value-readiness': typeof SidebarValueReadinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/artifacts'
    | '/company'
    | '/dashboard'
    | '/data-catalog'
    | '/edit'
    | '/gaps'
    | '/knowledge'
    | '/profile'
    | '/rules'
    | '/source-systems'
    | '/taxonomy'
    | '/value-readiness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/artifacts'
    | '/company'
    | '/dashboard'
    | '/data-catalog'
    | '/edit'
    | '/gaps'
    | '/knowledge'
    | '/profile'
    | '/rules'
    | '/source-systems'
    | '/taxonomy'
    | '/value-readiness'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/about'
    | '/_sidebar/analytics'
    | '/_sidebar/artifacts'
    | '/_sidebar/company'
    | '/_sidebar/dashboard'
    | '/_sidebar/data-catalog'
    | '/_sidebar/edit'
    | '/_sidebar/gaps'
    | '/_sidebar/knowledge'
    | '/_sidebar/profile'
    | '/_sidebar/rules'
    | '/_sidebar/source-systems'
    | '/_sidebar/taxonomy'
    | '/_sidebar/value-readiness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/value-readiness': {
      id: '/_sidebar/value-readiness'
      path: '/value-readiness'
      fullPath: '/value-readiness'
      preLoaderRoute: typeof SidebarValueReadinessRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/taxonomy': {
      id: '/_sidebar/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof SidebarTaxonomyRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/source-systems': {
      id: '/_sidebar/source-systems'
      path: '/source-systems'
      fullPath: '/source-systems'
      preLoaderRoute: typeof SidebarSourceSystemsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/rules': {
      id: '/_sidebar/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof SidebarRulesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/knowledge': {
      id: '/_sidebar/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof SidebarKnowledgeRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/gaps': {
      id: '/_sidebar/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof SidebarGapsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/edit': {
      id: '/_sidebar/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof SidebarEditRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/data-catalog': {
      id: '/_sidebar/data-catalog'
      path: '/data-catalog'
      fullPath: '/data-catalog'
      preLoaderRoute: typeof SidebarDataCatalogRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/company': {
      id: '/_sidebar/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof SidebarCompanyRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/artifacts': {
      id: '/_sidebar/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof SidebarArtifactsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/analytics': {
      id: '/_sidebar/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof SidebarAnalyticsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/about': {
      id: '/_sidebar/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SidebarAboutRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarAboutRoute: typeof SidebarAboutRoute
  SidebarAnalyticsRoute: typeof SidebarAnalyticsRoute
  SidebarArtifactsRoute: typeof SidebarArtifactsRoute
  SidebarCompanyRoute: typeof SidebarCompanyRoute
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarDataCatalogRoute: typeof SidebarDataCatalogRoute
  SidebarEditRoute: typeof SidebarEditRoute
  SidebarGapsRoute: typeof SidebarGapsRoute
  SidebarKnowledgeRoute: typeof SidebarKnowledgeRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarRulesRoute: typeof SidebarRulesRoute
  SidebarSourceSystemsRoute: typeof SidebarSourceSystemsRoute
  SidebarTaxonomyRoute: typeof SidebarTaxonomyRoute
  SidebarValueReadinessRoute: typeof SidebarValueReadinessRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarAboutRoute: SidebarAboutRoute,
  SidebarAnalyticsRoute: SidebarAnalyticsRoute,
  SidebarArtifactsRoute: SidebarArtifactsRoute,
  SidebarCompanyRoute: SidebarCompanyRoute,
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarDataCatalogRoute: SidebarDataCatalogRoute,
  SidebarEditRoute: SidebarEditRoute,
  SidebarGapsRoute: SidebarGapsRoute,
  SidebarKnowledgeRoute: SidebarKnowledgeRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarRulesRoute: SidebarRulesRoute,
  SidebarSourceSystemsRoute: SidebarSourceSystemsRoute,
  SidebarTaxonomyRoute: SidebarTaxonomyRoute,
  SidebarValueReadinessRoute: SidebarValueReadinessRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
