"""
Value-model build: link use cases to (a) canonical source systems and
(b) BHE affiliates, and seed the supporting dimension tables.

Why this job exists
-------------------
The Source System Browser (Phase 0 prior work) tells business users
"what data we have." This job answers the next question:
"what use cases can we deliver with that data, for whom, and what's missing?"

It produces three gold tables:

  bhe_gold.program_affiliate_map       (seed, customer-editable)
  bhe_gold.use_case_source_requirements (LLM-derived + manual override)
  bhe_gold.use_case_affiliates          (LLM-derived + manual override)

(bhe_gold.affiliates is now generated by the company-research wizard via
ai_query — see _ai_query_generate_affiliates in router.py. The CSV seed
path was retired.)

Pipeline (3 stages, each tagged + idempotent)
---------------------------------------------
1. derive_program_affiliate_map (LLM)
   Reads distinct programs from bhe_silver.silver_schemas and the
   subsidiary list from bhe_gold.affiliates, runs ONE ai_query call to
   produce program -> affiliate mappings (with primary/secondary
   strength), then MERGEs into bhe_gold.program_affiliate_map with
   is_user_edited preservation. Closed-vocab guards drop any LLM rows
   whose program/affiliate is outside the input lists. Replaces the old
   CSV-seed path (B-003 closure, 2026-05-05).

2. extract_unresolved_use_cases + apply_llm_mapping
   Selects every use_case in bhe_silver.use_cases that does not yet
   have any rows in use_case_source_requirements (bounds LLM cost to
   NEW use cases only), then runs one ai_query call per use case that
   returns BOTH required_sources and applicable_affiliates. The
   canonical source list and affiliate list are passed as closed
   vocabularies in the prompt. EXPLODEs the arrays and MERGEs into
   the two child tables. Manual rows (is_user_edited=true) are
   preserved.

3. validate
   Prints summary stats per table for quick sanity in job logs.

CLI
---
    --catalog                  default your_catalog
    --silver-schema            default bhe_silver
    --gold-schema              default bhe_gold
    --remap-unmapped           re-evaluate use cases that previously mapped only to 'Unmapped'
    --skip-llm                 skip stage 2 (program_affiliate_map LLM stage 1 still runs)
    --llm-endpoint             default databricks-claude-sonnet-4

Re-run safety
-------------
Idempotent. Manual edits (is_user_edited=true) are preserved across runs.
"""
from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import time

from pyspark.sql import SparkSession

try:
    _here = os.path.dirname(os.path.abspath(__file__))
except NameError:
    _here = (
        os.path.dirname(os.path.abspath(sys.argv[0]))
        if sys.argv and sys.argv[0]
        else os.getcwd()
    )
sys.path.insert(0, _here)
from _query_tag import tag_block, tagged_sql  # noqa: E402

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("build_value_model")

MODULE = "build_value_model"
DEFAULT_LLM_ENDPOINT = "databricks-claude-sonnet-4"


def _sql_str(s: str) -> str:
    return "'" + (s or "").replace("'", "''") + "'"


# =====================================================================
# Stage 1 (retired): affiliates seeding
#
# Affiliates are now generated by the company-research wizard via
# ai_query (see _ai_query_generate_affiliates in src/app/.../router.py).
# This job no longer reads affiliates_seed.csv. Anyone needing custom
# affiliate entries uses the Edit Center, which sets is_user_edited=true
# so the wizard's MERGE never overwrites them. The `_resolve_csv` /
# `affiliates_seed.csv` paths were deleted in 2026-05-12.
# =====================================================================


# =====================================================================
# Stage 2: derive bhe_gold.program_affiliate_map via LLM
#
# Closes B-003 (program_affiliate_map_seed.csv portion). Mirrors the
# LLM-generate-then-MERGE pattern that company-research uses for
# `bhe_gold.affiliates` (see _ai_query_generate_affiliates in router.py).
#
# Inputs:
#   - distinct programs from bhe_silver.silver_schemas (the actual
#     programs the customer ingested; 'Unknown' is skipped)
#   - bhe_gold.affiliates (the LLM-generated subsidiary list)
#
# Output: bhe_gold.program_affiliate_map (program, affiliate_name,
#         affiliation_strength, notes), MERGEd with is_user_edited
#         preservation so any rows the customer edited via the Edit
#         Center survive subsequent re-runs.
#
# If either input is empty (greenfield deploy with no schemas ingested
# yet, or affiliates not yet generated), the stage logs and skips —
# the next job run will pick it up. We never write a row with
# is_user_edited=true here; that flag is reserved for the Edit Center.
# =====================================================================
def stage_llm_program_map(spark: SparkSession, *, catalog: str, silver: str,
                          gold: str, llm_endpoint: str) -> None:
    tbl = f"`{catalog}`.`{gold}`.`program_affiliate_map`"

    with tag_block(spark, module=MODULE, submodule="llm_program_map_ddl"):
        spark.sql(tagged_sql(f"""
            CREATE TABLE IF NOT EXISTS {tbl} (
                program              STRING NOT NULL COMMENT 'silver_schemas.program value',
                affiliate_name       STRING NOT NULL COMMENT 'FK -> affiliates.affiliate_name',
                affiliation_strength STRING          COMMENT 'primary | secondary',
                notes                STRING,
                is_user_edited       BOOLEAN,
                updated_at           TIMESTAMP
            )
            USING DELTA
            COMMENT 'Bridge: catalog program -> affiliate. LLM-generated, customer-editable; manual edits survive.'
        """, module=MODULE, submodule="llm_program_map_ddl"))

    # Inputs: distinct ingested programs and the affiliate list.
    schemas_tbl = f"`{catalog}`.`{silver}`.`silver_schemas`"
    affiliates_tbl = f"`{catalog}`.`{gold}`.`affiliates`"

    programs = [
        r["program"] for r in spark.sql(tagged_sql(f"""
            SELECT DISTINCT program
            FROM {schemas_tbl}
            WHERE program IS NOT NULL
              AND program != ''
              AND program != 'Unknown'
        """, module=MODULE, submodule="llm_program_map_inputs")).collect()
    ]
    if not programs:
        logger.warning("Stage 2: no programs found in silver_schemas (skipping LLM mapping). "
                       "Run ingest first.")
        return

    aff_rows = spark.sql(tagged_sql(f"""
        SELECT affiliate_name,
               COALESCE(description, '') AS description
        FROM {affiliates_tbl}
        ORDER BY affiliate_name
    """, module=MODULE, submodule="llm_program_map_inputs")).collect()
    affiliates = [(r["affiliate_name"], r["description"]) for r in aff_rows]
    if not affiliates:
        logger.warning("Stage 2: no affiliates in gold.affiliates (skipping LLM mapping). "
                       "Run company research first.")
        return

    # Build the prompt: closed-vocabulary lists for both program and
    # affiliate so the LLM can't invent values that fail the FK on MERGE.
    programs_block = "\n".join(f"- {p}" for p in programs)
    aff_block = "\n".join(
        f"- {a[0]}" + (f" ({a[1][:140]})" if a[1] else "")
        for a in affiliates
    )
    # Use the first PROGRAM and the first AFFILIATE as concrete shape
    # examples so the LLM sees the field naming and value types up front
    # (without these examples models often invent keys like
    # `program_name` / `subsidiary` instead of the schema we need).
    # `json.dumps` handles all the escaping (quotes, unicode, etc).
    example = json.dumps({
        "mappings": [{
            "program": programs[0],
            "affiliate_name": affiliates[0][0],
            "affiliation_strength": "primary",
            "notes": "1-sentence rationale",
        }],
    }, ensure_ascii=False, indent=2)
    prompt = (
        "You are a data architect mapping internal data programs to operating "
        "subsidiaries (affiliates) of a company. For each PROGRAM below, decide "
        "which AFFILIATE(S) it most likely belongs to, based on naming "
        "conventions and the affiliate's business description.\n\n"
        f"PROGRAMS:\n{programs_block}\n\n"
        f"AFFILIATES:\n{aff_block}\n\n"
        "Rules:\n"
        "1. A program may map to one or more affiliates. Use 'primary' for the "
        "main owner and 'secondary' for shared / cross-cutting programs.\n"
        "2. NEVER invent affiliate names — use the exact strings from AFFILIATES.\n"
        "3. NEVER invent program names — use the exact strings from PROGRAMS.\n"
        "4. If you cannot reasonably map a program, omit it (don't guess).\n"
        "5. The 'notes' field should be a 1-sentence rationale.\n"
        "6. Return JSON ONLY, no prose, no fenced code block, no "
        "leading/trailing commentary.\n\n"
        "Return JSON with EXACTLY this shape (top-level key MUST be "
        "\"mappings\"; do NOT invent other keys):\n"
        f"{example}"
    )
    response_schema = (
        "mappings ARRAY<STRUCT<program:STRING, affiliate_name:STRING, "
        "affiliation_strength:STRING, notes:STRING>>"
    )

    with tag_block(spark, module=MODULE, submodule="llm_program_map_query"):
        t0 = time.time()
        spark.sql(tagged_sql(f"""
            CREATE OR REPLACE TEMPORARY VIEW _pmap_llm AS
            SELECT ai_query(
                       {_sql_str(llm_endpoint)},
                       {_sql_str(prompt)},
                       failOnError => false,
                       modelParameters => named_struct(
                           'max_tokens', 4000,
                           'temperature', 0.0
                       )
                   ) AS resp
        """, module=MODULE, submodule="llm_program_map_query"))
        logger.info(f"Stage 2: LLM program-map query finished in {time.time()-t0:.1f}s")

    # Parse: strip optional ```json fences (the LLM sometimes adds them
    # despite responseFormat hints), then `from_json` to a typed array.
    with tag_block(spark, module=MODULE, submodule="llm_program_map_parse"):
        spark.sql(tagged_sql(f"""
            CREATE OR REPLACE TEMPORARY VIEW _pmap_parsed AS
            WITH cleaned AS (
                SELECT regexp_replace(
                           regexp_replace(resp.result, '^```\\\\w*\\\\n?', ''),
                           '\\\\n?```$', ''
                       ) AS clean_json
                FROM _pmap_llm
                WHERE resp.result IS NOT NULL
            )
            SELECT from_json(TRIM(clean_json), {_sql_str(response_schema)}) AS p
            FROM cleaned
        """, module=MODULE, submodule="llm_program_map_parse"))

    # Closed-vocab guards: drop any LLM rows whose program or affiliate
    # is outside the input lists. This is paranoia — rule (2)/(3) of the
    # prompt already cover it — but FKs aren't free in Delta and a single
    # garbage row would persist until manually deleted.
    progs_in = ",".join(_sql_str(p) for p in programs)
    affs_in = ",".join(_sql_str(a[0]) for a in affiliates)

    with tag_block(spark, module=MODULE, submodule="llm_program_map_merge"):
        merge_count = spark.sql(tagged_sql(f"""
            WITH exploded AS (
                SELECT m.program            AS program,
                       m.affiliate_name     AS affiliate_name,
                       LOWER(COALESCE(m.affiliation_strength, 'primary'))
                                            AS affiliation_strength,
                       COALESCE(m.notes, '') AS notes
                FROM _pmap_parsed
                LATERAL VIEW explode(p.mappings) t AS m
            ),
            filtered AS (
                SELECT program, affiliate_name,
                       CASE WHEN affiliation_strength NOT IN ('primary','secondary')
                            THEN 'primary' ELSE affiliation_strength END AS affiliation_strength,
                       notes
                FROM exploded
                WHERE program IN ({progs_in})
                  AND affiliate_name IN ({affs_in})
            )
            SELECT COUNT(*) AS c FROM filtered
        """, module=MODULE, submodule="llm_program_map_merge")).collect()[0]["c"]

        if merge_count == 0:
            logger.warning("Stage 2: LLM produced 0 valid program->affiliate rows after "
                           "vocab-filter. Leaving program_affiliate_map untouched.")
            return

        spark.sql(tagged_sql(f"""
            MERGE INTO {tbl} AS t
            USING (
                WITH exploded AS (
                    SELECT m.program            AS program,
                           m.affiliate_name     AS affiliate_name,
                           LOWER(COALESCE(m.affiliation_strength, 'primary'))
                                                AS affiliation_strength,
                           COALESCE(m.notes, '') AS notes
                    FROM _pmap_parsed
                    LATERAL VIEW explode(p.mappings) t AS m
                )
                SELECT program, affiliate_name,
                       CASE WHEN affiliation_strength NOT IN ('primary','secondary')
                            THEN 'primary' ELSE affiliation_strength END AS affiliation_strength,
                       notes
                FROM exploded
                WHERE program IN ({progs_in})
                  AND affiliate_name IN ({affs_in})
            ) AS s
            ON t.program = s.program AND t.affiliate_name = s.affiliate_name
            WHEN MATCHED AND COALESCE(t.is_user_edited, false) = false THEN
                UPDATE SET
                    t.affiliation_strength = s.affiliation_strength,
                    t.notes                = s.notes,
                    t.updated_at           = current_timestamp()
            WHEN NOT MATCHED THEN
                INSERT (program, affiliate_name, affiliation_strength, notes,
                        is_user_edited, updated_at)
                VALUES (s.program, s.affiliate_name, s.affiliation_strength,
                        s.notes, false, current_timestamp())
        """, module=MODULE, submodule="llm_program_map_merge"))

    logger.info(f"Stage 2: LLM-derived {merge_count} program->affiliate rows into {tbl}")


# =====================================================================
# Stage 3 + 4: LLM-derive use_case_source_requirements + use_case_affiliates
# =====================================================================
def _dedup_target_table(spark: SparkSession, *, table_fqn: str,
                        partition_keys: list[str], order_clause: str,
                        submodule: str) -> None:
    """
    Self-healing dedup: collapse rows that share the same composite key.
    Always preserves the manual / highest-priority row per group.
    """
    with tag_block(spark, module=MODULE, submodule=submodule):
        n_before = spark.sql(tagged_sql(
            f"SELECT COUNT(*) AS c FROM {table_fqn}",
            module=MODULE, submodule=submodule,
        )).collect()[0]["c"]
        if n_before == 0:
            return
        partition = ", ".join(partition_keys)
        spark.sql(tagged_sql(f"""
            INSERT OVERWRITE {table_fqn}
            SELECT * EXCEPT (rn) FROM (
                SELECT *,
                    ROW_NUMBER() OVER (
                        PARTITION BY {partition}
                        ORDER BY {order_clause}
                    ) AS rn
                FROM {table_fqn}
            ) WHERE rn = 1
        """, module=MODULE, submodule=submodule))
        n_after = spark.sql(tagged_sql(
            f"SELECT COUNT(*) AS c FROM {table_fqn}",
            module=MODULE, submodule=submodule,
        )).collect()[0]["c"]
        removed = n_before - n_after
        if removed > 0:
            logger.warning(
                f"Self-healing dedup on {table_fqn}: "
                f"{n_before} -> {n_after} (removed {removed})"
            )


def _ensure_llm_target_tables(spark: SparkSession, *, catalog: str, gold: str) -> None:
    src_req_tbl = f"`{catalog}`.`{gold}`.`use_case_source_requirements`"
    uc_aff_tbl = f"`{catalog}`.`{gold}`.`use_case_affiliates`"

    with tag_block(spark, module=MODULE, submodule="llm_targets_ddl"):
        spark.sql(tagged_sql(f"""
            CREATE TABLE IF NOT EXISTS {src_req_tbl} (
                use_case_id        STRING NOT NULL COMMENT 'FK -> use_cases.id',
                required_canonical STRING NOT NULL COMMENT 'FK -> source_system_canonical.canonical, or "Unmapped"',
                necessity          STRING          COMMENT 'must_have | nice_to_have',
                data_need_excerpt  STRING          COMMENT 'Source phrase from data_requirements that triggered the mapping',
                confidence         STRING          COMMENT 'high | med | low',
                mapped_by          STRING          COMMENT 'llm | manual',
                is_user_edited     BOOLEAN,
                mapped_at          TIMESTAMP
            )
            USING DELTA
            COMMENT 'Use case -> required source systems. LLM-derived with closed-vocab prompt; analyst overrides preserved.'
        """, module=MODULE, submodule="llm_targets_ddl"))

        spark.sql(tagged_sql(f"""
            CREATE TABLE IF NOT EXISTS {uc_aff_tbl} (
                use_case_id    STRING NOT NULL COMMENT 'FK -> use_cases.id',
                affiliate_name STRING NOT NULL COMMENT 'FK -> affiliates.affiliate_name',
                applicability  STRING          COMMENT 'primary | secondary',
                rationale      STRING,
                mapped_by      STRING          COMMENT 'llm | manual',
                is_user_edited BOOLEAN,
                mapped_at      TIMESTAMP
            )
            USING DELTA
            COMMENT 'Use case -> applicable BHE affiliates. LLM-derived; analyst overrides preserved.'
        """, module=MODULE, submodule="llm_targets_ddl"))


def _build_prompt_template(canon: list[str], affiliates: list[str]) -> str:
    canon_list = "\n".join(f"- {c}" for c in canon)
    aff_list = "\n".join(f"- {a}" for a in affiliates)
    return (
        "You are a data governance assistant for Berkshire Hathaway Energy (BHE), "
        "an electric and gas utility holding company.\n\n"
        "TASK: Given a use case (name + description + data requirements), output a JSON object "
        "with TWO arrays:\n"
        "  1. required_sources: each item is "
        '{"canonical": <one of allowed sources OR "Unmapped">, '
        '"necessity": "must_have"|"nice_to_have", '
        '"excerpt": <the short data-requirement phrase that maps to this source>, '
        '"confidence": "high"|"med"|"low"}\n'
        "  2. applicable_affiliates: each item is "
        '{"affiliate": <one of allowed affiliates>, '
        '"applicability": "primary"|"secondary", '
        '"rationale": <1 short sentence>}\n\n'
        "RULES:\n"
        "- The `canonical` value MUST be exactly one of the strings in the ALLOWED SOURCES list, "
        'or the literal string "Unmapped" if no source matches.\n'
        "- The `affiliate` value MUST be exactly one of the strings in the ALLOWED AFFILIATES list. "
        'If the use case is BHE-wide or spans more than two affiliates, use "Multi-Affiliate".\n'
        "- Mark a source must_have if the use case cannot be delivered without it; otherwise nice_to_have.\n"
        "- Mark an affiliate primary if the use case is most directly relevant to that operating company.\n"
        "- Output minified JSON only. No markdown. No explanation.\n\n"
        "ALLOWED SOURCES:\n" + canon_list + "\n\n"
        "ALLOWED AFFILIATES:\n" + aff_list + "\n\n"
        "USE CASE:\n"
    )


def stage_llm_mapping(spark: SparkSession, *, catalog: str, silver: str,
                      gold: str, llm_endpoint: str, remap_unmapped: bool) -> None:
    uc_tbl = f"`{catalog}`.`{silver}`.`use_cases`"
    canon_tbl = f"`{catalog}`.`{gold}`.`source_system_canonical`"
    aff_tbl = f"`{catalog}`.`{gold}`.`affiliates`"
    src_req_tbl = f"`{catalog}`.`{gold}`.`use_case_source_requirements`"
    uc_aff_tbl = f"`{catalog}`.`{gold}`.`use_case_affiliates`"

    _ensure_llm_target_tables(spark, catalog=catalog, gold=gold)

    # Self-heal any existing duplicates in the target tables. Same composite-key
    # contract as the MERGE: (use_case_id, required_canonical) and
    # (use_case_id, affiliate_name). Manual + must_have rows win.
    _dedup_target_table(
        spark,
        table_fqn=src_req_tbl,
        partition_keys=["use_case_id", "required_canonical"],
        order_clause=(
            "CASE WHEN COALESCE(is_user_edited,false) THEN 0 ELSE 1 END, "
            "CASE WHEN mapped_by='manual' THEN 0 ELSE 1 END, "
            "CASE WHEN necessity='must_have' THEN 0 ELSE 1 END, "
            "CASE confidence WHEN 'high' THEN 0 WHEN 'med' THEN 1 ELSE 2 END, "
            "mapped_at DESC NULLS LAST"
        ),
        submodule="dedup_source_requirements",
    )
    _dedup_target_table(
        spark,
        table_fqn=uc_aff_tbl,
        partition_keys=["use_case_id", "affiliate_name"],
        order_clause=(
            "CASE WHEN COALESCE(is_user_edited,false) THEN 0 ELSE 1 END, "
            "CASE WHEN mapped_by='manual' THEN 0 ELSE 1 END, "
            "CASE WHEN applicability='primary' THEN 0 ELSE 1 END, "
            "mapped_at DESC NULLS LAST"
        ),
        submodule="dedup_use_case_affiliates",
    )

    with tag_block(spark, module=MODULE, submodule="llm_load_vocab"):
        canon = [
            r["canonical"] for r in spark.sql(tagged_sql(
                f"SELECT canonical FROM {canon_tbl} WHERE is_active = true "
                "ORDER BY canonical",
                module=MODULE, submodule="llm_load_vocab",
            )).collect()
        ]
        affiliates = [
            r["affiliate_name"] for r in spark.sql(tagged_sql(
                f"SELECT affiliate_name FROM {aff_tbl} WHERE is_active = true "
                "ORDER BY affiliate_name",
                module=MODULE, submodule="llm_load_vocab",
            )).collect()
        ]
    if not canon or not affiliates:
        logger.error("Stage 4: canonical or affiliate vocab is empty. "
                     "Run stages 1-2 first. Skipping LLM stage.")
        return
    logger.info(f"Loaded {len(canon)} canonical sources, {len(affiliates)} affiliates.")

    where_unresolved = (
        "uc.id NOT IN (SELECT DISTINCT use_case_id FROM " + src_req_tbl + ") "
        "OR uc.id NOT IN (SELECT DISTINCT use_case_id FROM " + uc_aff_tbl + ")"
    )
    if remap_unmapped:
        where_unresolved += (
            f" OR uc.id IN (SELECT use_case_id FROM {src_req_tbl} "
            "GROUP BY use_case_id "
            "HAVING MAX(CASE WHEN required_canonical = 'Unmapped' THEN 1 ELSE 0 END) = 1 "
            "AND COUNT(DISTINCT required_canonical) = 1)"
        )

    with tag_block(spark, module=MODULE, submodule="llm_extract_unresolved"):
        unresolved = spark.sql(tagged_sql(f"""
            SELECT
                uc.id                     AS use_case_id,
                COALESCE(uc.use_case_name, '') AS use_case_name,
                COALESCE(uc.description, '')   AS description,
                COALESCE(uc.data_requirements, '[]') AS data_requirements
            FROM {uc_tbl} uc
            WHERE COALESCE(uc.id, '') != ''
              AND ({where_unresolved})
        """, module=MODULE, submodule="llm_extract_unresolved")).collect()

    if not unresolved:
        logger.info("Stage 4: no unresolved use cases. Skipping LLM stage.")
        return
    logger.info(f"Stage 4: {len(unresolved)} use cases need LLM resolution.")

    prompt_template = _build_prompt_template(canon, affiliates)

    values = ",\n".join(
        f"({_sql_str(r['use_case_id'])}, "
        f"{_sql_str(r['use_case_name'])}, "
        f"{_sql_str(r['description'])}, "
        f"{_sql_str(r['data_requirements'])})"
        for r in unresolved
    )

    with tag_block(spark, module=MODULE, submodule="llm_ai_query"):
        t0 = time.time()
        spark.sql(tagged_sql(f"""
            CREATE OR REPLACE TEMPORARY VIEW _val_llm AS
            SELECT use_case_id,
                   ai_query(
                       {_sql_str(llm_endpoint)},
                       concat(
                           {_sql_str(prompt_template)},
                           'Name: ', use_case_name, '\\n',
                           'Description: ', description, '\\n',
                           'Data requirements: ', data_requirements
                       ),
                       failOnError => false,
                       modelParameters => named_struct(
                           'max_tokens', 1200,
                           'temperature', 0.0
                       )
                   ) AS resp
            FROM (
                SELECT * FROM (VALUES {values})
                AS v(use_case_id, use_case_name, description, data_requirements)
            )
        """, module=MODULE, submodule="llm_ai_query"))
        cnt = spark.sql(tagged_sql(
            "SELECT COUNT(*) AS c FROM _val_llm",
            module=MODULE, submodule="llm_ai_query_count",
        )).collect()[0]["c"]
        logger.info(f"LLM stage produced {cnt} responses in {time.time()-t0:.1f}s")

    canon_in_list = ",".join(_sql_str(c) for c in canon) + ",'Unmapped'"
    aff_in_list = ",".join(_sql_str(a) for a in affiliates)

    with tag_block(spark, module=MODULE, submodule="llm_parse"):
        spark.sql(tagged_sql(f"""
            CREATE OR REPLACE TEMPORARY VIEW _val_parsed AS
            WITH cleaned AS (
                SELECT use_case_id,
                       regexp_replace(
                           regexp_replace(resp.result, '^```\\\\w*\\\\n?', ''),
                           '\\\\n?```$', ''
                       ) AS clean_json
                FROM _val_llm
                WHERE resp.result IS NOT NULL
            )
            SELECT use_case_id,
                   from_json(TRIM(clean_json),
                             'required_sources ARRAY<STRUCT<canonical:STRING, necessity:STRING, excerpt:STRING, confidence:STRING>>, '
                             'applicable_affiliates ARRAY<STRUCT<affiliate:STRING, applicability:STRING, rationale:STRING>>'
                   ) AS p
            FROM cleaned
        """, module=MODULE, submodule="llm_parse"))

    with tag_block(spark, module=MODULE, submodule="llm_write_sources"):
        spark.sql(tagged_sql(f"""
            MERGE INTO {src_req_tbl} AS t
            USING (
                WITH exploded AS (
                    SELECT
                        use_case_id,
                        CASE
                            WHEN s.canonical IN ({canon_in_list}) THEN s.canonical
                            ELSE 'Unmapped'
                        END AS required_canonical,
                        CASE
                            WHEN lower(s.necessity) IN ('must_have','must','required') THEN 'must_have'
                            ELSE 'nice_to_have'
                        END AS necessity,
                        s.excerpt   AS data_need_excerpt,
                        COALESCE(s.confidence, 'med') AS confidence
                    FROM _val_parsed
                    LATERAL VIEW explode(COALESCE(p.required_sources, array())) AS s
                )
                SELECT use_case_id, required_canonical, necessity,
                       data_need_excerpt, confidence FROM (
                    SELECT *,
                        ROW_NUMBER() OVER (
                            PARTITION BY use_case_id, required_canonical
                            ORDER BY
                                CASE WHEN necessity='must_have' THEN 0 ELSE 1 END,
                                CASE confidence WHEN 'high' THEN 0
                                                WHEN 'med' THEN 1 ELSE 2 END
                        ) AS rn
                    FROM exploded
                ) WHERE rn = 1
            ) AS src
            ON t.use_case_id = src.use_case_id
               AND t.required_canonical = src.required_canonical
            WHEN MATCHED AND COALESCE(t.is_user_edited, false) = false
                          AND COALESCE(t.mapped_by, '') != 'manual' THEN
                UPDATE SET
                    t.necessity         = src.necessity,
                    t.data_need_excerpt = src.data_need_excerpt,
                    t.confidence        = src.confidence,
                    t.mapped_by         = 'llm',
                    t.mapped_at         = current_timestamp()
            WHEN NOT MATCHED THEN
                INSERT (use_case_id, required_canonical, necessity,
                        data_need_excerpt, confidence, mapped_by,
                        is_user_edited, mapped_at)
                VALUES (src.use_case_id, src.required_canonical, src.necessity,
                        src.data_need_excerpt, src.confidence, 'llm',
                        false, current_timestamp())
        """, module=MODULE, submodule="llm_write_sources"))

    with tag_block(spark, module=MODULE, submodule="llm_write_affiliates"):
        spark.sql(tagged_sql(f"""
            MERGE INTO {uc_aff_tbl} AS t
            USING (
                WITH exploded AS (
                    SELECT
                        use_case_id,
                        CASE
                            WHEN a.affiliate IN ({aff_in_list}) THEN a.affiliate
                            ELSE 'Multi-Affiliate'
                        END AS affiliate_name,
                        CASE
                            WHEN lower(a.applicability) = 'primary' THEN 'primary'
                            ELSE 'secondary'
                        END AS applicability,
                        a.rationale
                    FROM _val_parsed
                    LATERAL VIEW explode(COALESCE(p.applicable_affiliates, array())) AS a
                )
                SELECT use_case_id, affiliate_name, applicability, rationale FROM (
                    SELECT *,
                        ROW_NUMBER() OVER (
                            PARTITION BY use_case_id, affiliate_name
                            ORDER BY CASE WHEN applicability='primary' THEN 0 ELSE 1 END
                        ) AS rn
                    FROM exploded
                ) WHERE rn = 1
            ) AS src
            ON t.use_case_id = src.use_case_id
               AND t.affiliate_name = src.affiliate_name
            WHEN MATCHED AND COALESCE(t.is_user_edited, false) = false
                          AND COALESCE(t.mapped_by, '') != 'manual' THEN
                UPDATE SET
                    t.applicability = src.applicability,
                    t.rationale     = src.rationale,
                    t.mapped_by     = 'llm',
                    t.mapped_at     = current_timestamp()
            WHEN NOT MATCHED THEN
                INSERT (use_case_id, affiliate_name, applicability,
                        rationale, mapped_by, is_user_edited, mapped_at)
                VALUES (src.use_case_id, src.affiliate_name, src.applicability,
                        src.rationale, 'llm', false, current_timestamp())
        """, module=MODULE, submodule="llm_write_affiliates"))


# =====================================================================
# Stage 5: validate
# =====================================================================
def stage_validate(spark: SparkSession, *, catalog: str, silver: str, gold: str) -> None:
    uc_tbl = f"`{catalog}`.`{silver}`.`use_cases`"
    aff_tbl = f"`{catalog}`.`{gold}`.`affiliates`"
    pmap_tbl = f"`{catalog}`.`{gold}`.`program_affiliate_map`"
    src_req_tbl = f"`{catalog}`.`{gold}`.`use_case_source_requirements`"
    uc_aff_tbl = f"`{catalog}`.`{gold}`.`use_case_affiliates`"

    with tag_block(spark, module=MODULE, submodule="validate"):
        rows = spark.sql(tagged_sql(f"""
            SELECT
                (SELECT COUNT(*) FROM {uc_tbl})         AS use_cases,
                (SELECT COUNT(*) FROM {aff_tbl})        AS affiliates,
                (SELECT COUNT(*) FROM {pmap_tbl})       AS program_map_rows,
                (SELECT COUNT(*) FROM {src_req_tbl})    AS source_requirement_rows,
                (SELECT COUNT(DISTINCT use_case_id) FROM {src_req_tbl}) AS uc_with_sources,
                (SELECT COUNT(*) FROM {src_req_tbl}
                 WHERE required_canonical = 'Unmapped') AS unmapped_source_rows,
                (SELECT COUNT(*) FROM {uc_aff_tbl})     AS uc_affiliate_rows,
                (SELECT COUNT(DISTINCT use_case_id) FROM {uc_aff_tbl}) AS uc_with_affiliates
        """, module=MODULE, submodule="validate")).collect()
    r = rows[0].asDict() if rows else {}
    logger.info("=== Value model summary ===")
    for k, v in r.items():
        logger.info(f"  {k:30s} = {v}")


# =====================================================================
# Main
# =====================================================================
def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", default="your_catalog")
    parser.add_argument("--silver-schema", default="bhe_silver")
    parser.add_argument("--gold-schema", default="bhe_gold")
    # `--program-map-seed` retired in favor of LLM-driven mapping
    # (B-003 closure). Kept as a hidden no-op so existing job
    # configurations don't fail on `unrecognized argument` after a
    # bundle redeploy. New callers should drop the flag.
    parser.add_argument("--program-map-seed", default="",
                        help=argparse.SUPPRESS)
    parser.add_argument("--reseed", action="store_true",
                        help="(reserved) re-derive program_affiliate_map even if rows exist; "
                             "current behavior is always-merge with is_user_edited preservation.")
    parser.add_argument("--remap-unmapped", action="store_true",
                        help="Re-evaluate use cases whose only source mapping is 'Unmapped'.")
    parser.add_argument("--skip-llm", action="store_true",
                        help="Skip the use-case ↔ source/affiliate LLM stage. "
                             "The program_affiliate_map LLM stage is always run because "
                             "Stage 4 depends on it.")
    parser.add_argument("--llm-endpoint", default=DEFAULT_LLM_ENDPOINT)
    args = parser.parse_args()

    if args.program_map_seed:
        logger.warning("--program-map-seed is deprecated and ignored (B-003 closure). "
                       "program_affiliate_map is now LLM-derived from silver_schemas + "
                       "gold.affiliates.")

    spark = SparkSession.builder.appName("build_value_model").getOrCreate()

    logger.info(f"catalog={args.catalog} silver={args.silver_schema} gold={args.gold_schema}")
    logger.info(f"skip_llm={args.skip_llm} remap_unmapped={args.remap_unmapped}")

    stage_llm_program_map(spark, catalog=args.catalog,
                          silver=args.silver_schema, gold=args.gold_schema,
                          llm_endpoint=args.llm_endpoint)

    if not args.skip_llm:
        stage_llm_mapping(spark, catalog=args.catalog, silver=args.silver_schema,
                          gold=args.gold_schema, llm_endpoint=args.llm_endpoint,
                          remap_unmapped=args.remap_unmapped)
    else:
        logger.info("Skipping LLM stage (--skip-llm).")

    stage_validate(spark, catalog=args.catalog, silver=args.silver_schema,
                   gold=args.gold_schema)


if __name__ == "__main__":
    main()
